### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by dqve**
Hey, I added an animator for the menu toggle button, kindly check it out.

### CODE REVIEW

**Comment by aladearchives** [comment]
Your Join Url does not refer properly to the join page

**Comment by dqve** [comment]
I didn't make any change to the join link though, please review the changes and rewrite as you deem fit

**Review by aladearchives — APPROVED** [review]

**Comment by aladearchives** [comment]
@dqve the changes were regarding the menu button. Yikes. How did I not see that earlier. Many thanks

**Comment by dqve** [comment]
> @dqve the changes were regarding the menu button. Yikes. How did I not see that earlier. Many thanks

@aladearchives Tell me if it works or doesn't please, I legit didn't test it with your code before I pushed, I'm sorry

**Comment by aladearchives** [comment]
@dqve it didn't work. Nav Bar Hamburger Icon now redirects to another url. Did you add another library?

**Comment by dqve** [comment]
> @dqve it didn't work. Nav Bar Hamburger Icon now redirects to another url. Did you add another library?

Yeah I did, to warp the Navbar initial icon to the "x" icon on click, I'd have to pull the codebase and test it out now

**Pull request merged**
